<?php

namespace AppBundle\Repository;

/**
 * CapteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapteurRepository extends \Doctrine\ORM\EntityRepository
{
}
