<?php

namespace AppBundle\Repository;

/**
 * LigneFacturationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFacturationRepository extends \Doctrine\ORM\EntityRepository
{
}
