<?php

namespace AppBundle\Repository;

/**
 * QrCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QrCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
