<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Mapping as ORM;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
