AppBundle\Entity\Tarif:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TarifRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
        description:
            type: text
        prix:
            type: float
    lifecycleCallbacks: {  }
